### ISSUE TITLE
Same icon for external http- and https-links

### ISSUE THREAD

**Issue by thkoester** [thaider/Tweeki#281]
Tweeki displays a lock item for http**s**-links and the right-up arrow for http-links (MediaWiki 1.43 + Tweeki 5.39)

Https is more or less the default nowadays. E.g. the Vector 2022 skin does not differentiate these and IMHO Tweeki should also not.

Possible solutions:

1. Change CSS in next release
2. Add configuration option
3. Add How-to with CSS-code for `MediaWiki:Tweeki.css`

For others with the same problem: This content in `MediaWiki:Tweeki.css` worked for me:

`#content a.external[href^="https://"], 
.link-https {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAVklEQVR4Xn3PgQkAMQhDUXfqTu7kTtkpd5RA8AInfArtQ2iRXFWT2QedAfttj2FsPIOE1eCOlEuoWWjgzYaB/IkeGOrxXhqB+uA9Bfcm0lAZuh+YIeAD+cAqSz4kCMUAAAAASUVORK5CYII=) center right no-repeat;
    padding-right: 13px;
}
`

**Comment by soerendohmen** [comment]
I agree that changing the default in Tweeki could make sense if the maintainer wants that direction.

Modern MediaWiki skinning seems to have moved away from the old special `.link-https` / lock-icon treatment. MediaWiki core removed `.link-https` from the external link selector in 1.38 (T298431), so skins using the current core external-link styling no longer get that special HTTPS lock treatment by default.

See:

- https://www.mediawiki.org/wiki/MediaWiki_1.38/wmf.17
- https://www.mediawiki.org/wiki/Help:Links/en#External_links

This is mostly a Tweeki-specific issue because Tweeki still ships its own legacy-style external link icon rules, including the old HTTPS/lock-icon distinction. Modern MediaWiki core skinning removed `.link-https` from the external link selector in 1.38 (T298431), so skins using the current core external-link styling do not usually show this HTTPS-specific lock icon anymore.

For installations that want to change this locally, I would avoid editing Tweeki's core skin files directly. Since this is a Tweeki-specific styling issue, the override should go into the Tweeki-specific site stylesheet, for example `MediaWiki:Tweeki.css`, rather than into the skin's core files.

After saving `MediaWiki:Tweeki.css`, users may need to bypass the browser cache or purge the page cache before the change is visible.

Example CSS:

```css
#content a.external[href^="https://"],
#content .link-https {
  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAVklEQVR4Xn3PgQkAMQhDUXfqTu7kTtkpd5RA8AInfArtQ2iRXFWT2QedAfttj2FsPIOE1eCOlEuoWWjgzYaB/IkeGOrxXhqB+uA9Bfcm0lAZuh+YIeAD+cAqSz4kCMUAAAAASUVORK5CYII=) center right no-repeat;
  padding-right: 13px;
}
```

So from my point of view:

1. If the maintainer wants HTTPS and HTTP links to look the same by default, this should be changed in Tweeki's external link styles.
2. If an installation just wants local behavior, it should be done through the Tweeki-specific site stylesheet, such as `MediaWiki:Tweeki.css`, rather than by patching core skin files.
